FROM nasanccs/pytorch-caney:latest
LABEL maintainer="jordan.a.caraballo-vega@nasa.gov"

ENV ABOVE_SHRUBS_VERSION=main

RUN pip install torchgeo==0.5.2 rioxarray==0.15.0 albumentations==1.3.1 rasterio==1.3.10 \
    torchmetrics==1.3.1 lightly==1.4.25 h5py==3.10.0 geobench==1.0.0 mlflow==2.14.3 \
    lightning==2.2.5 mmcv==2.0.0 ftfy regex openmim
RUN pip install git+https://github.com/IBM/terratorch.git

HEALTHCHECK NONE
ENTRYPOINT [""]
