FROM nasanccs/pytorch-caney:latest
LABEL maintainer="jordan.a.caraballo-vega@nasa.gov"

ENV ABOVE_SHRUBS_VERSION=main

RUN pip install torchgeo albumentations \
    torchmetrics lightly h5py geobench mlflow \
    lightning mmcv ftfy regex openmim
RUN pip install git+https://github.com/IBM/terratorch.git

HEALTHCHECK NONE
ENTRYPOINT [""]
